import = ["/home/alex/.config/alacritty/key_bindings.toml", "/home/alex/.config/alacritty/themes/theme.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[scrolling]
history = 50000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_title = false
opacity = 0.9
#decorations = "none"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 8
y = 8
